[package]

name = "COST"
version = "0.0.2"
authors = ["Frank McSherry <fmcsherry@me.com>", "AdityaAtulTewari <adityaatewari@gmail.com>"]
edition = "2021"

[dependencies]
docopt="*"
byteorder="*"
memmap="0.7"
lz4="*"
clap = { version = "4.5.3", features = ["derive"] }
