[env]
UID = { script = ["id -u"] }
GID = { script = ["id -g"] }
UNAME = { script = ["id -un"] }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.dockerbuild]
command = "docker"
args = ["build", "--build-arg=UNAME=${USER}", "--build-arg=UID=${UID}", "--build-arg=GID=${GID}", "-t", "cost:latest", "docker/"]

[tasks.docker]
command = "docker"
args = ["run", "-v", "/home/${UNAME}/.vim:/home/${UNAME}/.vim", "-v", "${CARGO_MAKE_WORKING_DIRECTORY}:/cost", "-ti", "cost:latest"]
dependencies = ["dockerbuild"]
