# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2023. University of Texas at Austin. All rights reserved.

name: Docker / Ubuntu 22.04 / Build and Test
run-name: docker-ubuntu-2204 performed by @${{ github.triggering_actor }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

ubuntu-2204-docker:
  name: cargo
  runs-on: self-hosted
  permissions:
    contests: read
    packages: write

  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0
      lfs: 'true'
      submodules: recursive

  - name: Format
      timeout-minutes: 1
      run: |
        cargo ci-fmt

  - name: Debug Tests
      timeout-minutes: 10
      run: |
        cargo ci-test

  - name: Release Tests
      timeout-minutes: 10
      run: |
        cargo ci-test-release
